###
GET http://localhost:8080/analyzer/match/1cee6c78-50c3-4246-8440-ea84b4e9ede9/player/ss_barl

###
GET http://localhost:8080/analyzer/match/1cee6c78-50c3-4246-8440-ea84b4e9ede9/player/LSWW1

###
GET http://localhost:8080/analyzer/match/1cee6c78-50c3-4246-8440-ea84b4e9ede9/player/Mr_POLOO

###
GET http://localhost:8080/analyzer/match/1cee6c78-50c3-4246-8440-ea84b4e9ede9/player/Patriot_Engineer